version: '3'

services:
  web:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development